steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag_scrape_pipeline', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag_scrape_pipeline']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','rag-scrape-pipeline',
        '--image','gcr.io/$PROJECT_ID/rag_scrape_pipeline',
        '--region','us-west1',
        '--platform','managed',
        '--allow-unauthenticated'
      ]

timeout: '1200s'
options:
  logging: LEGACY

